### ISSUE TITLE
Update for axum 0.6

### ISSUE THREAD

**Issue by blaenk** [LeoniePhiline/axum-csrf-sync-pattern#12]
I'm sure you're already aware but either way may be useful to have a tracking issue for this.

Changelog including breaking changes available [here](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#060-25-november-2022).

Thank you for this crate!

**Comment by LeoniePhiline** [comment]
Yes, I had been waiting for https://github.com/maxcountryman/axum-sessions/pull/8 to get merged first.

So good to see https://github.com/tokio-rs/axum/releases/tag/axum-v0.6.0 released! :) 🎉

**Comment by LeoniePhiline** [comment]
Fixed with 6ac6a40260bf41dcbb9af638922d340a1956fc0f.
